name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2
#        shell: micromamba-shell {0}

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
#        shell: micromamba-shell {0}
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_BUILD: yum install epel-release && yum install -y root root-minuit2 root-fumili healpix-c++-devel

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
