name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #[ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: "auto64"
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_BEFORE_BUILD_MACOS: brew install root healpix
          CIBW_BEFORE_BUILD_LINUX: yum install epel-release && yum install -y root root-minuit2 root-fumili root-fftw root-genvector healpix-c++-devel
          CIBW_SKIP: pp* *-musllinux_x86_64
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  deploy_pypi:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-20.04
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    needs: build_wheels
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/download-artifact@v2
        with:
          path: ./
      - name: build pycbc for pypi
        run: |
          python3 -m build --sdist
          mv artifact/* dist/
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
